# Generated by Django 3.0.3 on 2021-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210408_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='simage',
            field=models.ImageField(default='0.jpeg', upload_to='media'),
        ),
    ]
