# Generated by Django 3.0.3 on 2021-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_service_simage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rprice',
            field=models.IntegerField(default=1000),
        ),
    ]
