# Generated by Django 3.0.3 on 2021-04-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_rprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rprice',
        ),
    ]
