# Generated by Django 3.0.3 on 2021-04-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_room_rprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sname',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
