# Generated by Django 3.0.3 on 2021-04-07 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('memail', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=5)),
                ('level', models.CharField(choices=[('B', 'Basic'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Platinum')], max_length=1)),
                ('profile_pic', models.ImageField(blank=True, upload_to='media')),
                ('last_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gemail', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Member')),
            ],
        ),
    ]
