# Generated by Django 3.0.3 on 2021-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210407_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
