# Generated by Django 3.0.3 on 2021-04-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210407_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='mid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
