# Generated by Django 3.0.3 on 2021-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210407_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memail',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
