# Generated by Django 3.0.3 on 2021-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210407_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_visit',
            field=models.DateField(blank=True),
        ),
    ]
