# Generated by Django 3.0.3 on 2021-04-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210407_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_visit',
        ),
    ]
