# Generated by Django 3.0.3 on 2021-04-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('room', '0002_auto_20210407_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_no', models.AutoField(primary_key=True, serialize=False)),
                ('plantype', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('cost', models.IntegerField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Guest')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_dtno', models.IntegerField()),
                ('No_adults', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')])),
                ('No_children', models.IntegerField(choices=[(0, '0'), (1, '1')])),
                ('book_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room_type')),
            ],
            options={
                'unique_together': {('book_no', 'book_dtno')},
            },
        ),
    ]
