# Generated by Django 3.0.3 on 2021-04-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20210409_1905'),
        ('booking', '0002_service_in_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_detail',
            name='rno',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
    ]
