# Generated by Django 3.0.3 on 2021-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210409_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking_detail',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking_detail',
            constraint=models.UniqueConstraint(fields=('book_no', 'book_dtno'), name='unique_together'),
        ),
    ]
