# Generated by Django 3.0.3 on 2021-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210409_2224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service_in_room',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='service_in_room',
            constraint=models.UniqueConstraint(fields=('sid', 'book_dtno'), name='unique'),
        ),
    ]
